In [2]:
import numpy as np
list_ = [ '1', '2','3' ,'4', '5']
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data types of the variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array. The data type of list_ will be list, and the data type of array_list will be numpy.ndarray.

# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']  # Python list
array_list = np.array(object=list_)  # NumPy array

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")


Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there will be a difference in the data type of the elements present in list_ and array_list after converting array_list to a NumPy array with a specified data type (dtype=int). The elements in list_ will remain as strings (str), while the elements in array_list will be converted to integers (int).

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']  # Python list
array_list = np.array(object=list_, dtype=int)  # NumPy array with elements as integers

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")


Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.int64'>
Element: 2, Type: <class 'numpy.int64'>
Element: 3, Type: <class 'numpy.int64'>
Element: 4, Type: <class 'numpy.int64'>
Element: 5, Type: <class 'numpy.int64'>


In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


# Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
 ## (ii) size

You can use the `shape` and `size` attributes of a NumPy array to find the required characteristics of the `num_array`. Here's the code to do that:

```python
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]  # Python list of lists
num_array = np.array(object=num_list)  # NumPy array

# Find and print the shape of num_array
print("Shape of num_array:", num_array.shape)

# Find and print the size of num_array
print("Size of num_array:", num_array.size)
```

When you run this code, you will get the following output:

```
Shape of num_array: (2, 3)
Size of num_array: 6
```

### Explanation:
- **Shape**: The `shape` attribute returns a tuple representing the dimensions of the array. In this case, `(2, 3)` indicates that `num_array` has 2 rows and 3 columns.
- **Size**: The `size` attribute returns the total number of elements in the array. Here, `num_array` contains 6 elements in total.

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [7]:


# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [8]:


# Create a 5x5 identity matrix using np.eye
identity_matrix_eye = np.eye(5)

# Print the matrix
print("Identity matrix using np.eye:")
print(identity_matrix_eye)


Identity matrix using np.eye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
